/*
 * Team API
 *  The team API lets you manage users, departments, locations, and cards. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: developer-access@brex.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.Money;
import com.konfigthis.client.model.SpendDuration;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.LocalDate;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CardSpendControls
 */
public class CardSpendControlsTest {
    private final CardSpendControls model = new CardSpendControls();

    /**
     * Model tests for CardSpendControls
     */
    @Test
    public void testCardSpendControls() {
        // TODO: test CardSpendControls
    }

    /**
     * Test the property 'spendLimit'
     */
    @Test
    public void spendLimitTest() {
        // TODO: test spendLimit
    }

    /**
     * Test the property 'spendAvailable'
     */
    @Test
    public void spendAvailableTest() {
        // TODO: test spendAvailable
    }

    /**
     * Test the property 'spendDuration'
     */
    @Test
    public void spendDurationTest() {
        // TODO: test spendDuration
    }

    /**
     * Test the property 'reason'
     */
    @Test
    public void reasonTest() {
        // TODO: test reason
    }

    /**
     * Test the property 'lockAfterDate'
     */
    @Test
    public void lockAfterDateTest() {
        // TODO: test lockAfterDate
    }

}
