/*
 * Team API
 *  The team API lets you manage users, departments, locations, and cards. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: developer-access@brex.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.ThreeDomainSecureEnabledPreference;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CreateCardRequestCardAttributePreferences
 */
public class CreateCardRequestCardAttributePreferencesTest {
    private final CreateCardRequestCardAttributePreferences model = new CreateCardRequestCardAttributePreferences();

    /**
     * Model tests for CreateCardRequestCardAttributePreferences
     */
    @Test
    public void testCreateCardRequestCardAttributePreferences() {
        // TODO: test CreateCardRequestCardAttributePreferences
    }

    /**
     * Test the property 'threeDomainSecureEnabledPreference'
     */
    @Test
    public void threeDomainSecureEnabledPreferenceTest() {
        // TODO: test threeDomainSecureEnabledPreference
    }

}
