/*
 * Team API
 *  The team API lets you manage users, departments, locations, and cards. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: developer-access@brex.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.CardMailingAddress;
import com.konfigthis.client.model.CardType;
import com.konfigthis.client.model.CreateCardRequestCardAttributePreferences;
import com.konfigthis.client.model.CreateCardRequestSpendControls;
import com.konfigthis.client.model.LimitType;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CreateCardRequest
 */
public class CreateCardRequestTest {
    private final CreateCardRequest model = new CreateCardRequest();

    /**
     * Model tests for CreateCardRequest
     */
    @Test
    public void testCreateCardRequest() {
        // TODO: test CreateCardRequest
    }

    /**
     * Test the property 'owner'
     */
    @Test
    public void ownerTest() {
        // TODO: test owner
    }

    /**
     * Test the property 'cardName'
     */
    @Test
    public void cardNameTest() {
        // TODO: test cardName
    }

    /**
     * Test the property 'cardType'
     */
    @Test
    public void cardTypeTest() {
        // TODO: test cardType
    }

    /**
     * Test the property 'limitType'
     */
    @Test
    public void limitTypeTest() {
        // TODO: test limitType
    }

    /**
     * Test the property 'spendControls'
     */
    @Test
    public void spendControlsTest() {
        // TODO: test spendControls
    }

    /**
     * Test the property 'mailingAddress'
     */
    @Test
    public void mailingAddressTest() {
        // TODO: test mailingAddress
    }

    /**
     * Test the property 'metadata'
     */
    @Test
    public void metadataTest() {
        // TODO: test metadata
    }

    /**
     * Test the property 'cardAttributePreferences'
     */
    @Test
    public void cardAttributePreferencesTest() {
        // TODO: test cardAttributePreferences
    }

}
