/*
 * Team API
 *  The team API lets you manage users, departments, locations, and cards. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: developer-access@brex.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets CardStatus
 */
@JsonAdapter(CardStatus.Adapter.class)public enum CardStatus {
  
  ACTIVE("ACTIVE"),
  
  SHIPPED("SHIPPED"),
  
  LOCKED("LOCKED"),
  
  TERMINATED("TERMINATED");

  private String value;

  CardStatus(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static CardStatus fromValue(String value) {
    for (CardStatus b : CardStatus.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<CardStatus> {
    @Override
    public void write(final JsonWriter jsonWriter, final CardStatus enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public CardStatus read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return CardStatus.fromValue(value);
    }
  }
}

