/*
 * Team API
 *  The team API lets you manage users, departments, locations, and cards. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: developer-access@brex.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 *  Reason for card termination. 
 */
@JsonAdapter(ChangeCardReason.Adapter.class)public enum ChangeCardReason {
  
  CARD_DAMAGED("CARD_DAMAGED"),
  
  CARD_LOST("CARD_LOST"),
  
  CARD_NOT_RECEIVED("CARD_NOT_RECEIVED"),
  
  DO_NOT_NEED_PHYSICAL_CARD("DO_NOT_NEED_PHYSICAL_CARD"),
  
  DO_NOT_NEED_VIRTUAL_CARD("DO_NOT_NEED_VIRTUAL_CARD"),
  
  FRAUD("FRAUD"),
  
  OTHER("OTHER");

  private String value;

  ChangeCardReason(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static ChangeCardReason fromValue(String value) {
    for (ChangeCardReason b : ChangeCardReason.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<ChangeCardReason> {
    @Override
    public void write(final JsonWriter jsonWriter, final ChangeCardReason enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public ChangeCardReason read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return ChangeCardReason.fromValue(value);
    }
  }
}

