/*
 * Team API
 *  The team API lets you manage users, departments, locations, and cards. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: developer-access@brex.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.CardMailingAddress;
import com.konfigthis.client.model.CardType;
import com.konfigthis.client.model.CreateCardRequestCardAttributePreferences;
import com.konfigthis.client.model.CreateCardRequestSpendControls;
import com.konfigthis.client.model.LimitType;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 *  The &#x60;spend_controls&#x60; field is required when &#x60;limit_type&#x60; &#x3D; &#x60;CARD&#x60;. The &#x60;shipping_address&#x60; field is required for physical cards, and the first 2 lines of the address must be under 60 characters long. 
 */
@ApiModel(description = " The `spend_controls` field is required when `limit_type` = `CARD`. The `shipping_address` field is required for physical cards, and the first 2 lines of the address must be under 60 characters long. ")@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class CreateCardRequest {
  public static final String SERIALIZED_NAME_OWNER = "owner";
  @SerializedName(SERIALIZED_NAME_OWNER)
  private Object owner = null;

  public static final String SERIALIZED_NAME_CARD_NAME = "card_name";
  @SerializedName(SERIALIZED_NAME_CARD_NAME)
  private String cardName;

  public static final String SERIALIZED_NAME_CARD_TYPE = "card_type";
  @SerializedName(SERIALIZED_NAME_CARD_TYPE)
  private CardType cardType;

  public static final String SERIALIZED_NAME_LIMIT_TYPE = "limit_type";
  @SerializedName(SERIALIZED_NAME_LIMIT_TYPE)
  private LimitType limitType;

  public static final String SERIALIZED_NAME_SPEND_CONTROLS = "spend_controls";
  @SerializedName(SERIALIZED_NAME_SPEND_CONTROLS)
  private CreateCardRequestSpendControls spendControls;

  public static final String SERIALIZED_NAME_MAILING_ADDRESS = "mailing_address";
  @SerializedName(SERIALIZED_NAME_MAILING_ADDRESS)
  private CardMailingAddress mailingAddress;

  public static final String SERIALIZED_NAME_METADATA = "metadata";
  @SerializedName(SERIALIZED_NAME_METADATA)
  private Map<String, String> metadata = null;

  public static final String SERIALIZED_NAME_CARD_ATTRIBUTE_PREFERENCES = "card_attribute_preferences";
  @SerializedName(SERIALIZED_NAME_CARD_ATTRIBUTE_PREFERENCES)
  private CreateCardRequestCardAttributePreferences cardAttributePreferences;

  public CreateCardRequest() {
  }

  public CreateCardRequest owner(Object owner) {
    
    
    
    
    this.owner = owner;
    return this;
  }

   /**
   * Get owner
   * @return owner
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(required = true, value = "")

  public Object getOwner() {
    return owner;
  }


  public void setOwner(Object owner) {
    
    
    
    this.owner = owner;
  }


  public CreateCardRequest cardName(String cardName) {
    
    
    if (cardName != null && cardName.length() < 1) {
      throw new IllegalArgumentException("Invalid value for cardName. Length must be greater than or equal to 1.");
    }
    
    this.cardName = cardName;
    return this;
  }

   /**
   * Get cardName
   * @return cardName
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public String getCardName() {
    return cardName;
  }


  public void setCardName(String cardName) {
    
    
    if (cardName != null && cardName.length() < 1) {
      throw new IllegalArgumentException("Invalid value for cardName. Length must be greater than or equal to 1.");
    }
    this.cardName = cardName;
  }


  public CreateCardRequest cardType(CardType cardType) {
    
    
    
    
    this.cardType = cardType;
    return this;
  }

   /**
   * Get cardType
   * @return cardType
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public CardType getCardType() {
    return cardType;
  }


  public void setCardType(CardType cardType) {
    
    
    
    this.cardType = cardType;
  }


  public CreateCardRequest limitType(LimitType limitType) {
    
    
    
    
    this.limitType = limitType;
    return this;
  }

   /**
   * Get limitType
   * @return limitType
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public LimitType getLimitType() {
    return limitType;
  }


  public void setLimitType(LimitType limitType) {
    
    
    
    this.limitType = limitType;
  }


  public CreateCardRequest spendControls(CreateCardRequestSpendControls spendControls) {
    
    
    
    
    this.spendControls = spendControls;
    return this;
  }

   /**
   * Get spendControls
   * @return spendControls
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public CreateCardRequestSpendControls getSpendControls() {
    return spendControls;
  }


  public void setSpendControls(CreateCardRequestSpendControls spendControls) {
    
    
    
    this.spendControls = spendControls;
  }


  public CreateCardRequest mailingAddress(CardMailingAddress mailingAddress) {
    
    
    
    
    this.mailingAddress = mailingAddress;
    return this;
  }

   /**
   * Get mailingAddress
   * @return mailingAddress
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public CardMailingAddress getMailingAddress() {
    return mailingAddress;
  }


  public void setMailingAddress(CardMailingAddress mailingAddress) {
    
    
    
    this.mailingAddress = mailingAddress;
  }


  public CreateCardRequest metadata(Map<String, String> metadata) {
    
    
    
    
    this.metadata = metadata;
    return this;
  }

  public CreateCardRequest putMetadataItem(String key, String metadataItem) {
    if (this.metadata == null) {
      this.metadata = new HashMap<>();
    }
    this.metadata.put(key, metadataItem);
    return this;
  }

   /**
   *  Set of key value pairs associated with this object. Please do not store any personally identifiable or sensitive information here. Limitations: maximum of 50 keys, keys cannot exceed 40 characters, values cannot exceed 500 characters.  
   * @return metadata
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = " Set of key value pairs associated with this object. Please do not store any personally identifiable or sensitive information here. Limitations: maximum of 50 keys, keys cannot exceed 40 characters, values cannot exceed 500 characters.  ")

  public Map<String, String> getMetadata() {
    return metadata;
  }


  public void setMetadata(Map<String, String> metadata) {
    
    
    
    this.metadata = metadata;
  }


  public CreateCardRequest cardAttributePreferences(CreateCardRequestCardAttributePreferences cardAttributePreferences) {
    
    
    
    
    this.cardAttributePreferences = cardAttributePreferences;
    return this;
  }

   /**
   * Get cardAttributePreferences
   * @return cardAttributePreferences
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public CreateCardRequestCardAttributePreferences getCardAttributePreferences() {
    return cardAttributePreferences;
  }


  public void setCardAttributePreferences(CreateCardRequestCardAttributePreferences cardAttributePreferences) {
    
    
    
    this.cardAttributePreferences = cardAttributePreferences;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the CreateCardRequest instance itself
   */
  public CreateCardRequest putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateCardRequest createCardRequest = (CreateCardRequest) o;
    return Objects.equals(this.owner, createCardRequest.owner) &&
        Objects.equals(this.cardName, createCardRequest.cardName) &&
        Objects.equals(this.cardType, createCardRequest.cardType) &&
        Objects.equals(this.limitType, createCardRequest.limitType) &&
        Objects.equals(this.spendControls, createCardRequest.spendControls) &&
        Objects.equals(this.mailingAddress, createCardRequest.mailingAddress) &&
        Objects.equals(this.metadata, createCardRequest.metadata) &&
        Objects.equals(this.cardAttributePreferences, createCardRequest.cardAttributePreferences)&&
        Objects.equals(this.additionalProperties, createCardRequest.additionalProperties);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(owner, cardName, cardType, limitType, spendControls, mailingAddress, metadata, cardAttributePreferences, additionalProperties);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateCardRequest {\n");
    sb.append("    owner: ").append(toIndentedString(owner)).append("\n");
    sb.append("    cardName: ").append(toIndentedString(cardName)).append("\n");
    sb.append("    cardType: ").append(toIndentedString(cardType)).append("\n");
    sb.append("    limitType: ").append(toIndentedString(limitType)).append("\n");
    sb.append("    spendControls: ").append(toIndentedString(spendControls)).append("\n");
    sb.append("    mailingAddress: ").append(toIndentedString(mailingAddress)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    cardAttributePreferences: ").append(toIndentedString(cardAttributePreferences)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("owner");
    openapiFields.add("card_name");
    openapiFields.add("card_type");
    openapiFields.add("limit_type");
    openapiFields.add("spend_controls");
    openapiFields.add("mailing_address");
    openapiFields.add("metadata");
    openapiFields.add("card_attribute_preferences");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("owner");
    openapiRequiredFields.add("card_name");
    openapiRequiredFields.add("card_type");
    openapiRequiredFields.add("limit_type");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to CreateCardRequest
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!CreateCardRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in CreateCardRequest is not found in the empty JSON string", CreateCardRequest.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : CreateCardRequest.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      if (!jsonObj.get("card_name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `card_name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("card_name").toString()));
      }
      // validate the optional field `spend_controls`
      if (jsonObj.get("spend_controls") != null && !jsonObj.get("spend_controls").isJsonNull()) {
        CreateCardRequestSpendControls.validateJsonObject(jsonObj.getAsJsonObject("spend_controls"));
      }
      // validate the optional field `mailing_address`
      if (jsonObj.get("mailing_address") != null && !jsonObj.get("mailing_address").isJsonNull()) {
        CardMailingAddress.validateJsonObject(jsonObj.getAsJsonObject("mailing_address"));
      }
      // validate the optional field `card_attribute_preferences`
      if (jsonObj.get("card_attribute_preferences") != null && !jsonObj.get("card_attribute_preferences").isJsonNull()) {
        CreateCardRequestCardAttributePreferences.validateJsonObject(jsonObj.getAsJsonObject("card_attribute_preferences"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CreateCardRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CreateCardRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CreateCardRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CreateCardRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<CreateCardRequest>() {
           @Override
           public void write(JsonWriter out, CreateCardRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public CreateCardRequest read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             CreateCardRequest instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of CreateCardRequest given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of CreateCardRequest
  * @throws IOException if the JSON string is invalid with respect to CreateCardRequest
  */
  public static CreateCardRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CreateCardRequest.class);
  }

 /**
  * Convert an instance of CreateCardRequest to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

