/*
 * Team API
 *  The team API lets you manage users, departments, locations, and cards. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: developer-access@brex.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 *  &#x60;limit_type &#x3D; CARD&#x60; for vendor cards. Vendor cards must have a &#x60;card_type&#x60; of &#x60;VIRTUAL&#x60;  and do not rely on the user specific limit.   For corporate cards, &#x60;limit_type &#x3D; USER&#x60;.  Learn more about different card types [here](https://support.brex.com/what-are-the-different-types-of-cards-i-can-get/). 
 */
@JsonAdapter(LimitType.Adapter.class)public enum LimitType {
  
  CARD("CARD"),
  
  USER("USER");

  private String value;

  LimitType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static LimitType fromValue(String value) {
    for (LimitType b : LimitType.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<LimitType> {
    @Override
    public void write(final JsonWriter jsonWriter, final LimitType enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public LimitType read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return LimitType.fromValue(value);
    }
  }
}

