/*
 * Team API
 *  The team API lets you manage users, departments, locations, and cards. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: developer-access@brex.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * SecureEmailForCardDetailsRequest
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class SecureEmailForCardDetailsRequest {
  public static final String SERIALIZED_NAME_RECIPIENT_EMAIL = "recipient_email";
  @SerializedName(SERIALIZED_NAME_RECIPIENT_EMAIL)
  private String recipientEmail;

  public static final String SERIALIZED_NAME_SENDER_NAME = "sender_name";
  @SerializedName(SERIALIZED_NAME_SENDER_NAME)
  private String senderName;

  public static final String SERIALIZED_NAME_MESSAGE = "message";
  @SerializedName(SERIALIZED_NAME_MESSAGE)
  private String message;

  public static final String SERIALIZED_NAME_EXPIRY_DAYS = "expiry_days";
  @SerializedName(SERIALIZED_NAME_EXPIRY_DAYS)
  private Integer expiryDays;

  public SecureEmailForCardDetailsRequest() {
  }

  public SecureEmailForCardDetailsRequest recipientEmail(String recipientEmail) {
    
    
    
    
    this.recipientEmail = recipientEmail;
    return this;
  }

   /**
   * Email address to send card details to
   * @return recipientEmail
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Email address to send card details to")

  public String getRecipientEmail() {
    return recipientEmail;
  }


  public void setRecipientEmail(String recipientEmail) {
    
    
    
    this.recipientEmail = recipientEmail;
  }


  public SecureEmailForCardDetailsRequest senderName(String senderName) {
    
    
    
    
    this.senderName = senderName;
    return this;
  }

   /**
   * Sender name. Shows up in the subject of the email
   * @return senderName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Sender name. Shows up in the subject of the email")

  public String getSenderName() {
    return senderName;
  }


  public void setSenderName(String senderName) {
    
    
    
    this.senderName = senderName;
  }


  public SecureEmailForCardDetailsRequest message(String message) {
    
    
    
    
    this.message = message;
    return this;
  }

   /**
   * Message to send with the card details
   * @return message
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Message to send with the card details")

  public String getMessage() {
    return message;
  }


  public void setMessage(String message) {
    
    
    
    this.message = message;
  }


  public SecureEmailForCardDetailsRequest expiryDays(Integer expiryDays) {
    
    if (expiryDays != null && expiryDays > 30) {
      throw new IllegalArgumentException("Invalid value for expiryDays. Must be less than or equal to 30.");
    }
    
    
    this.expiryDays = expiryDays;
    return this;
  }

   /**
   * Link expiry in number of days. Defaults to 30
   * maximum: 30
   * @return expiryDays
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Link expiry in number of days. Defaults to 30")

  public Integer getExpiryDays() {
    return expiryDays;
  }


  public void setExpiryDays(Integer expiryDays) {
    
    if (expiryDays != null && expiryDays > 30) {
      throw new IllegalArgumentException("Invalid value for expiryDays. Must be less than or equal to 30.");
    }
    
    this.expiryDays = expiryDays;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the SecureEmailForCardDetailsRequest instance itself
   */
  public SecureEmailForCardDetailsRequest putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SecureEmailForCardDetailsRequest secureEmailForCardDetailsRequest = (SecureEmailForCardDetailsRequest) o;
    return Objects.equals(this.recipientEmail, secureEmailForCardDetailsRequest.recipientEmail) &&
        Objects.equals(this.senderName, secureEmailForCardDetailsRequest.senderName) &&
        Objects.equals(this.message, secureEmailForCardDetailsRequest.message) &&
        Objects.equals(this.expiryDays, secureEmailForCardDetailsRequest.expiryDays)&&
        Objects.equals(this.additionalProperties, secureEmailForCardDetailsRequest.additionalProperties);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(recipientEmail, senderName, message, expiryDays, additionalProperties);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SecureEmailForCardDetailsRequest {\n");
    sb.append("    recipientEmail: ").append(toIndentedString(recipientEmail)).append("\n");
    sb.append("    senderName: ").append(toIndentedString(senderName)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    expiryDays: ").append(toIndentedString(expiryDays)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("recipient_email");
    openapiFields.add("sender_name");
    openapiFields.add("message");
    openapiFields.add("expiry_days");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to SecureEmailForCardDetailsRequest
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!SecureEmailForCardDetailsRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in SecureEmailForCardDetailsRequest is not found in the empty JSON string", SecureEmailForCardDetailsRequest.openapiRequiredFields.toString()));
        }
      }
      if ((jsonObj.get("recipient_email") != null && !jsonObj.get("recipient_email").isJsonNull()) && !jsonObj.get("recipient_email").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `recipient_email` to be a primitive type in the JSON string but got `%s`", jsonObj.get("recipient_email").toString()));
      }
      if ((jsonObj.get("sender_name") != null && !jsonObj.get("sender_name").isJsonNull()) && !jsonObj.get("sender_name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `sender_name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("sender_name").toString()));
      }
      if (!jsonObj.get("message").isJsonNull() && (jsonObj.get("message") != null && !jsonObj.get("message").isJsonNull()) && !jsonObj.get("message").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `message` to be a primitive type in the JSON string but got `%s`", jsonObj.get("message").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!SecureEmailForCardDetailsRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'SecureEmailForCardDetailsRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<SecureEmailForCardDetailsRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(SecureEmailForCardDetailsRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<SecureEmailForCardDetailsRequest>() {
           @Override
           public void write(JsonWriter out, SecureEmailForCardDetailsRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public SecureEmailForCardDetailsRequest read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             SecureEmailForCardDetailsRequest instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of SecureEmailForCardDetailsRequest given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of SecureEmailForCardDetailsRequest
  * @throws IOException if the JSON string is invalid with respect to SecureEmailForCardDetailsRequest
  */
  public static SecureEmailForCardDetailsRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, SecureEmailForCardDetailsRequest.class);
  }

 /**
  * Convert an instance of SecureEmailForCardDetailsRequest to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

