/*
 * Team API
 *  The team API lets you manage users, departments, locations, and cards. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: developer-access@brex.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 *      Spend limit refresh frequency     - MONTHLY: The spend limit refreshes every month     - QUARTERLY: The spend limit refreshes every quarter     - YEARLY: The spend limit refreshes every year     - ONE_TIME: The limit does not refresh 
 */
@JsonAdapter(SpendDuration.Adapter.class)public enum SpendDuration {
  
  MONTHLY("MONTHLY"),
  
  QUARTERLY("QUARTERLY"),
  
  YEARLY("YEARLY"),
  
  ONE_TIME("ONE_TIME");

  private String value;

  SpendDuration(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static SpendDuration fromValue(String value) {
    for (SpendDuration b : SpendDuration.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<SpendDuration> {
    @Override
    public void write(final JsonWriter jsonWriter, final SpendDuration enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public SpendDuration read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return SpendDuration.fromValue(value);
    }
  }
}

