/*
 * Team API
 *  The team API lets you manage users, departments, locations, and cards. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: developer-access@brex.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.Money;
import com.konfigthis.client.model.SpendDuration;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.LocalDate;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 *  When &#x60;limit_type &#x3D; CARD&#x60;, &#x60;spend_controls&#x60; must be set. When &#x60;limit type &#x3D; USER&#x60;, &#x60;spend_controls&#x60; must be &#x60;null&#x60;. 
 */
@ApiModel(description = " When `limit_type = CARD`, `spend_controls` must be set. When `limit type = USER`, `spend_controls` must be `null`. ")@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class SpendControlRequest {
  public static final String SERIALIZED_NAME_SPEND_LIMIT = "spend_limit";
  @SerializedName(SERIALIZED_NAME_SPEND_LIMIT)
  private Money spendLimit;

  public static final String SERIALIZED_NAME_SPEND_DURATION = "spend_duration";
  @SerializedName(SERIALIZED_NAME_SPEND_DURATION)
  private SpendDuration spendDuration;

  public static final String SERIALIZED_NAME_REASON = "reason";
  @SerializedName(SERIALIZED_NAME_REASON)
  private String reason;

  public static final String SERIALIZED_NAME_LOCK_AFTER_DATE = "lock_after_date";
  @SerializedName(SERIALIZED_NAME_LOCK_AFTER_DATE)
  private LocalDate lockAfterDate;

  public static final String SERIALIZED_NAME_PARENT_BUDGET_ID = "parent_budget_id";
  @SerializedName(SERIALIZED_NAME_PARENT_BUDGET_ID)
  private String parentBudgetId;

  public SpendControlRequest() {
  }

  public SpendControlRequest spendLimit(Money spendLimit) {
    
    
    
    
    this.spendLimit = spendLimit;
    return this;
  }

   /**
   * Get spendLimit
   * @return spendLimit
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public Money getSpendLimit() {
    return spendLimit;
  }


  public void setSpendLimit(Money spendLimit) {
    
    
    
    this.spendLimit = spendLimit;
  }


  public SpendControlRequest spendDuration(SpendDuration spendDuration) {
    
    
    
    
    this.spendDuration = spendDuration;
    return this;
  }

   /**
   * Get spendDuration
   * @return spendDuration
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public SpendDuration getSpendDuration() {
    return spendDuration;
  }


  public void setSpendDuration(SpendDuration spendDuration) {
    
    
    
    this.spendDuration = spendDuration;
  }


  public SpendControlRequest reason(String reason) {
    
    
    
    
    this.reason = reason;
    return this;
  }

   /**
   * Get reason
   * @return reason
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getReason() {
    return reason;
  }


  public void setReason(String reason) {
    
    
    
    this.reason = reason;
  }


  public SpendControlRequest lockAfterDate(LocalDate lockAfterDate) {
    
    
    
    
    this.lockAfterDate = lockAfterDate;
    return this;
  }

   /**
   * Get lockAfterDate
   * @return lockAfterDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public LocalDate getLockAfterDate() {
    return lockAfterDate;
  }


  public void setLockAfterDate(LocalDate lockAfterDate) {
    
    
    
    this.lockAfterDate = lockAfterDate;
  }


  public SpendControlRequest parentBudgetId(String parentBudgetId) {
    
    
    
    
    this.parentBudgetId = parentBudgetId;
    return this;
  }

   /**
   *  If using the Empower platform, a new &#x60;budget&#x60; will be created for this card. You can specify a &#x60;parent_budget&#x60; that your new &#x60;budget&#x60; will be nested under. If &#x60;parent_budget_id&#x60; is null, we will nest the new budget under the top-level account &#x60;budget&#x60;. 
   * @return parentBudgetId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = " If using the Empower platform, a new `budget` will be created for this card. You can specify a `parent_budget` that your new `budget` will be nested under. If `parent_budget_id` is null, we will nest the new budget under the top-level account `budget`. ")

  public String getParentBudgetId() {
    return parentBudgetId;
  }


  public void setParentBudgetId(String parentBudgetId) {
    
    
    
    this.parentBudgetId = parentBudgetId;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the SpendControlRequest instance itself
   */
  public SpendControlRequest putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SpendControlRequest spendControlRequest = (SpendControlRequest) o;
    return Objects.equals(this.spendLimit, spendControlRequest.spendLimit) &&
        Objects.equals(this.spendDuration, spendControlRequest.spendDuration) &&
        Objects.equals(this.reason, spendControlRequest.reason) &&
        Objects.equals(this.lockAfterDate, spendControlRequest.lockAfterDate) &&
        Objects.equals(this.parentBudgetId, spendControlRequest.parentBudgetId)&&
        Objects.equals(this.additionalProperties, spendControlRequest.additionalProperties);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(spendLimit, spendDuration, reason, lockAfterDate, parentBudgetId, additionalProperties);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SpendControlRequest {\n");
    sb.append("    spendLimit: ").append(toIndentedString(spendLimit)).append("\n");
    sb.append("    spendDuration: ").append(toIndentedString(spendDuration)).append("\n");
    sb.append("    reason: ").append(toIndentedString(reason)).append("\n");
    sb.append("    lockAfterDate: ").append(toIndentedString(lockAfterDate)).append("\n");
    sb.append("    parentBudgetId: ").append(toIndentedString(parentBudgetId)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("spend_limit");
    openapiFields.add("spend_duration");
    openapiFields.add("reason");
    openapiFields.add("lock_after_date");
    openapiFields.add("parent_budget_id");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("spend_limit");
    openapiRequiredFields.add("spend_duration");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to SpendControlRequest
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!SpendControlRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in SpendControlRequest is not found in the empty JSON string", SpendControlRequest.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : SpendControlRequest.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      // validate the required field `spend_limit`
      Money.validateJsonObject(jsonObj.getAsJsonObject("spend_limit"));
      if (!jsonObj.get("reason").isJsonNull() && (jsonObj.get("reason") != null && !jsonObj.get("reason").isJsonNull()) && !jsonObj.get("reason").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `reason` to be a primitive type in the JSON string but got `%s`", jsonObj.get("reason").toString()));
      }
      if (!jsonObj.get("parent_budget_id").isJsonNull() && (jsonObj.get("parent_budget_id") != null && !jsonObj.get("parent_budget_id").isJsonNull()) && !jsonObj.get("parent_budget_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `parent_budget_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("parent_budget_id").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!SpendControlRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'SpendControlRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<SpendControlRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(SpendControlRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<SpendControlRequest>() {
           @Override
           public void write(JsonWriter out, SpendControlRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public SpendControlRequest read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             SpendControlRequest instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of SpendControlRequest given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of SpendControlRequest
  * @throws IOException if the JSON string is invalid with respect to SpendControlRequest
  */
  public static SpendControlRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, SpendControlRequest.class);
  }

 /**
  * Convert an instance of SpendControlRequest to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

