/*
 * Team API
 *  The team API lets you manage users, departments, locations, and cards. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: developer-access@brex.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 *  Whether to enable 3-D secure protocol on this card.  
 */
@JsonAdapter(ThreeDomainSecureEnabledPreference.Adapter.class)public enum ThreeDomainSecureEnabledPreference {
  
  ENABLED("THREE_DOMAIN_SECURE_ENABLED"),
  
  DISABLED("THREE_DOMAIN_SECURE_DISABLED");

  private String value;

  ThreeDomainSecureEnabledPreference(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static ThreeDomainSecureEnabledPreference fromValue(String value) {
    for (ThreeDomainSecureEnabledPreference b : ThreeDomainSecureEnabledPreference.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<ThreeDomainSecureEnabledPreference> {
    @Override
    public void write(final JsonWriter jsonWriter, final ThreeDomainSecureEnabledPreference enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public ThreeDomainSecureEnabledPreference read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return ThreeDomainSecureEnabledPreference.fromValue(value);
    }
  }
}

