/*
 * Team API
 *  The team API lets you manage users, departments, locations, and cards. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: developer-access@brex.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 *  Acceptable user status for update. To suspend a user, set status to &#39;disabled&#39;. To unsuspend a user, set status to &#39;active&#39;. 
 */
@JsonAdapter(UpdateUserStatus.Adapter.class)public enum UpdateUserStatus {
  
  ACTIVE("ACTIVE"),
  
  DISABLED("DISABLED");

  private String value;

  UpdateUserStatus(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static UpdateUserStatus fromValue(String value) {
    for (UpdateUserStatus b : UpdateUserStatus.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<UpdateUserStatus> {
    @Override
    public void write(final JsonWriter jsonWriter, final UpdateUserStatus enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public UpdateUserStatus read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return UpdateUserStatus.fromValue(value);
    }
  }
}

