/*
 * Team API
 *  The team API lets you manage users, departments, locations, and cards. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: developer-access@brex.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Status of the user
 */
@JsonAdapter(UserStatus.Adapter.class)public enum UserStatus {
  
  INVITED("INVITED"),
  
  ACTIVE("ACTIVE"),
  
  CLOSED("CLOSED"),
  
  DISABLED("DISABLED"),
  
  DELETED("DELETED"),
  
  PENDING_ACTIVATION("PENDING_ACTIVATION"),
  
  INACTIVE("INACTIVE");

  private String value;

  UserStatus(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static UserStatus fromValue(String value) {
    for (UserStatus b : UserStatus.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<UserStatus> {
    @Override
    public void write(final JsonWriter jsonWriter, final UserStatus enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public UserStatus read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return UserStatus.fromValue(value);
    }
  }
}

