/*
 * Team API
 *  The team API lets you manage users, departments, locations, and cards. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: developer-access@brex.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.CreateDepartmentRequest;
import com.konfigthis.client.model.DepartmentResponse;
import com.konfigthis.client.model.PageDepartmentResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DepartmentsApi
 */
@Disabled
public class DepartmentsApiTest {

    private static DepartmentsApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new DepartmentsApi(apiClient);
    }

    /**
     *  Create department 
     *
     *  This endpoint creates a new department 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void addNewDepartmentTest() throws ApiException {
        String name = null;
        String description = null;
        String idempotencyKey = null;
        DepartmentResponse response = api.addNewDepartment(name)
                .description(description)
                .idempotencyKey(idempotencyKey)
                .execute();
        // TODO: test validations
    }

    /**
     *  Get department 
     *
     *  This endpoint gets a department by ID. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getByIdTest() throws ApiException {
        String id = null;
        DepartmentResponse response = api.getById(id)
                .execute();
        // TODO: test validations
    }

    /**
     *  List departments 
     *
     *  This endpoint lists all departments. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listAllTest() throws ApiException {
        String cursor = null;
        Integer limit = null;
        String name = null;
        PageDepartmentResponse response = api.listAll()
                .cursor(cursor)
                .limit(limit)
                .name(name)
                .execute();
        // TODO: test validations
    }

}
