/*
 * Team API
 *  The team API lets you manage users, departments, locations, and cards. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: developer-access@brex.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.CreateTitleRequest;
import com.konfigthis.client.model.PageTitleResponse;
import com.konfigthis.client.model.TitleResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TitlesApi
 */
@Disabled
public class TitlesApiTest {

    private static TitlesApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new TitlesApi(apiClient);
    }

    /**
     *  Create title 
     *
     *  This endpoint creates a new title 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createNewTitleTest() throws ApiException {
        String name = null;
        String idempotencyKey = null;
        TitleResponse response = api.createNewTitle(name)
                .idempotencyKey(idempotencyKey)
                .execute();
        // TODO: test validations
    }

    /**
     *  List titles 
     *
     *  This endpoint lists all titles. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getAllTest() throws ApiException {
        String cursor = null;
        Integer limit = null;
        String name = null;
        PageTitleResponse response = api.getAll()
                .cursor(cursor)
                .limit(limit)
                .name(name)
                .execute();
        // TODO: test validations
    }

    /**
     *  Get title 
     *
     *  This endpoint gets a title by ID. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getTitleByIdTest() throws ApiException {
        String id = null;
        TitleResponse response = api.getTitleById(id)
                .execute();
        // TODO: test validations
    }

}
