openapi: 3.0.1
info:
  contact:
    email: developer-access@brex.com
    name: Admin
    url: https://brex.com
  description: |2

    The team API lets you manage users, departments, locations, and cards.
  title: Team API
  version: "1.0"
  x-konfig-has-globally-required-security: true
servers:
- description: Production
  url: https://platform.brexapis.com
- description: "Staging (Note: This is not a sandbox. It will not work with customer\
    \ tokens.)"
  url: https://platform.staging.brexapps.com
security:
- OAuth2: []
tags:
- description: Endpoints for card management.
  name: Cards
- description: Endpoints for user management.
  name: Users
- description: Endpoints for location management.
  name: Locations
- description: Endpoints for department management.
  name: Departments
- description: Endpoints for title management.
  name: Titles
- name: Companies
paths:
  /v2/cards:
    get:
      description: |2

        Lists all cards by a `user_id`.
        Only cards with `limit_type = CARD` have `spend_controls`
      operationId: Cards_listByUserId
      security:
      - OAuth2:
        - cards.readonly
        - cards
      summary: |2

        List cards
      tags:
      - Cards
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--v2-cards
      x-accepts: application/json
    post:
      description: "\nCreates a new card.\nThe `spend_controls` field is required\
        \ when `limit_type` = `CARD`.\nThe `mailing_address` field is required for\
        \ physical cards and is the shipping address used to send the card; it is\
        \ not the same as the billing and mailing address used for online purchases.\n\
        The first 2 lines of this address must be under 60 characters long. Each user\
        \ can only have up to 10 active physical cards.\nFor Empower accounts, this\
        \ endpoint requires budget management. If your account does not have access\
        \ to budget management features, a 403 response status will be returned. \n\
        If this is the case and you want to gain access to this endpoint, please contact\
        \ Brex support.\n"
      operationId: Cards_createNewCard
      security:
      - OAuth2:
        - cards
      summary: |2

        Create card
      tags:
      - Cards
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--v2-cards
      x-content-type: application/json
      x-accepts: application/json
  /v2/cards/{id}:
    get:
      description: |2

        Retrieves a card by ID. Only cards with `limit_type = CARD` have `spend_controls`
      operationId: Cards_getById
      security:
      - OAuth2:
        - cards
        - cards.readonly
      summary: |2

        Get card
      tags:
      - Cards
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--v2-cards-id
      x-accepts: application/json
    put:
      description: |2

        Update an existing vendor card
      operationId: Cards_updateCard
      security:
      - OAuth2:
        - cards
      summary: |2

        Update card
      tags:
      - Cards
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-put--v2-cards-id
      x-content-type: application/json
      x-accepts: application/json
  /v2/cards/{id}/lock:
    post:
      description: |2

        Locks an existing, unlocked card. And the card owner will receive a notification about it.
      operationId: Cards_lockCard
      security:
      - OAuth2:
        - cards
      summary: |2

        Lock card
      tags:
      - Cards
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--v2-cards-id-lock
      x-content-type: application/json
      x-accepts: application/json
  /v2/cards/{id}/pan:
    get:
      description: |2

        Retrieves card number, CVV, and expiration date of a card by ID.
      operationId: Cards_getCardDetails
      security:
      - OAuth2:
        - cards.pan
      servers:
      - description: Production
        url: https://secure-platform.brexapis.com
      - description: "Staging (Note: This is not a sandbox. It will not work with\
          \ customer tokens.)"
        url: https://secure-platform.staging.brexapps.com
      summary: |2

        Get card number
      tags:
      - Cards
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--v2-cards-id-pan
      x-accepts: application/json
  /v2/cards/{id}/secure_email:
    post:
      description: |2

        Creates a secure email to send card number, CVV, and expiration date of a card by ID to the specified email.

        This endpoint is currently gated. If you would like to request access, please reach out to
        developer-access@brex.com
      operationId: Cards_createSecureEmail
      security:
      - OAuth2:
        - cards.pan
      summary: "\nCreate secure email to send card number \n"
      tags:
      - Cards
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--v2-cards-id-secure_email
      x-content-type: application/json
      x-accepts: application/json
  /v2/cards/{id}/terminate:
    post:
      description: |2

        Terminates an existing card. The card owner will receive a notification about it.
      operationId: Cards_terminateExistingCard
      security:
      - OAuth2:
        - cards
      summary: |2

        Terminate card
      tags:
      - Cards
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--v2-cards-id-terminate
      x-content-type: application/json
      x-accepts: application/json
  /v2/cards/{id}/unlock:
    post:
      description: |2

        Unlocks an existing card.
      operationId: Cards_unlockExistingCard
      security:
      - OAuth2:
        - cards
      summary: |2

        Unlock card
      tags:
      - Cards
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--v2-cards-id-unlock
      x-accepts: application/json
  /v2/company:
    get:
      description: |2

        This endpoint returns the company associated with the OAuth2 access token.
      operationId: Companies_getInfo
      security:
      - OAuth2:
        - companies.readonly
      summary: |2

        Get company
      tags:
      - Companies
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--v2-company
      x-accepts: application/json
  /v2/departments:
    get:
      description: |2

        This endpoint lists all departments.
      operationId: Departments_listAll
      security:
      - OAuth2:
        - departments
        - departments.readonly
      summary: |2

        List departments
      tags:
      - Departments
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--v2-departments
      x-accepts: application/json
    post:
      description: |2

        This endpoint creates a new department
      operationId: Departments_addNewDepartment
      security:
      - OAuth2:
        - departments
      summary: |2

        Create department
      tags:
      - Departments
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--v2-departments
      x-content-type: application/json
      x-accepts: application/json
  /v2/departments/{id}:
    get:
      description: |2

        This endpoint gets a department by ID.
      operationId: Departments_getById
      security:
      - OAuth2:
        - departments
        - departments.readonly
      summary: |2

        Get department
      tags:
      - Departments
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--v2-departments-id
      x-accepts: application/json
  /v2/locations:
    get:
      description: |2

        This endpoint lists all locations.
      operationId: Locations_getAllLocations
      security:
      - OAuth2:
        - locations
        - locations.readonly
      summary: |2

        List locations
      tags:
      - Locations
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--v2-locations
      x-accepts: application/json
    post:
      description: |2

        This endpoint creates a new location.
      operationId: Locations_addNewLocation
      security:
      - OAuth2:
        - locations
      summary: |2

        Create location
      tags:
      - Locations
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--v2-locations
      x-content-type: application/json
      x-accepts: application/json
  /v2/locations/{id}:
    get:
      description: |2

        This endpoint gets a location by ID.
      operationId: Locations_getLocationById
      security:
      - OAuth2:
        - locations
        - locations.readonly
      summary: |2

        Get location
      tags:
      - Locations
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--v2-locations-id
      x-accepts: application/json
  /v2/titles:
    get:
      description: |2

        This endpoint lists all titles.
      operationId: Titles_getAll
      security:
      - OAuth2:
        - titles
        - titles.readonly
      summary: |2

        List titles
      tags:
      - Titles
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--v2-titles
      x-accepts: application/json
    post:
      description: |2

        This endpoint creates a new title
      operationId: Titles_createNewTitle
      security:
      - OAuth2:
        - titles
      summary: |2

        Create title
      tags:
      - Titles
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--v2-titles
      x-content-type: application/json
      x-accepts: application/json
  /v2/titles/{id}:
    get:
      description: |2

        This endpoint gets a title by ID.
      operationId: Titles_getTitleById
      security:
      - OAuth2:
        - titles
        - titles.readonly
      summary: |2

        Get title
      tags:
      - Titles
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--v2-titles-id
      x-accepts: application/json
  /v2/users:
    get:
      description: |2

        This endpoint lists all users. To find a user id by email, you can filter using the `email` query parameter.
      operationId: Users_listUsers
      security:
      - OAuth2:
        - users
        - users.readonly
      summary: |2

        List users
      tags:
      - Users
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--v2-users
      x-accepts: application/json
    post:
      description: |2

        This endpoint invites a new user as an employee.
        To update user's role, check out [this article](https://support.brex.com/how-do-i-change-another-user-s-role/).
      operationId: Users_inviteNewEmployee
      security:
      - OAuth2:
        - users
      summary: |2

        Invite user
      tags:
      - Users
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--v2-users
      x-content-type: application/json
      x-accepts: application/json
  /v2/users/me:
    get:
      description: |2

        This endpoint returns the user associated with the OAuth2 access token.
      operationId: Users_getCurrentUser
      security:
      - OAuth2:
        - users
        - users.readonly
      summary: |2

        Get current user
      tags:
      - Users
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--v2-users-me
      x-accepts: application/json
  /v2/users/{id}:
    get:
      description: |2

        This endpoint gets a user by ID.
      operationId: Users_getUserById
      security:
      - OAuth2:
        - users
        - users.readonly
      summary: |2

        Get user
      tags:
      - Users
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--v2-users-id
      x-accepts: application/json
    put:
      description: |2

        This endpoint updates a user. Any parameters not provided will be left unchanged.
      operationId: Users_updateUser
      security:
      - OAuth2:
        - users
      summary: |2

        Update user
      tags:
      - Users
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-put--v2-users-id
      x-content-type: application/json
      x-accepts: application/json
  /v2/users/{id}/limit:
    get:
      description: |2

        This endpoint gets the monthly limit for the user including the monthly available limit.
      operationId: Users_getMonthlyLimit
      security:
      - OAuth2:
        - users
        - users.readonly
      summary: |2

        Get limit for the user
      tags:
      - Users
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--v2-users-id-limit
      x-accepts: application/json
    post:
      description: "\nThis endpoint sets the monthly limit for a user. \nThe limit\
        \ amount must be non-negative. \nTo unset the monthly limit of the user, just\
        \ set `monthly_limit` to null.\n"
      operationId: Users_setMonthlyLimit
      security:
      - OAuth2:
        - users
      summary: |2

        Set limit for the user
      tags:
      - Users
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--v2-users-id-limit
      x-content-type: application/json
      x-accepts: application/json
components:
  securitySchemes:
    OAuth2:
      description: OAuth2 security scheme
      flows:
        authorizationCode:
          authorizationUrl: https://accounts-api.brex.com/oauth2/default/v1/authorize
          scopes:
            openid: openid
            offline_access: offline access
            users.readonly: View user data
            users: View and manage user data
            locations.readonly: View location data
            locations: View and manage location data
            departments.readonly: View department data
            departments: View and manage department data
            titles: View and manage title data
            titles.readonly: View title data
            cards: View and manage card data
            cards.readonly: View card data
            cards.pan: View and Send card number data
          tokenUrl: https://accounts-api.brex.com/oauth2/default/v1/token
      type: oauth2
      x-konfig-globally-required-security: true
x-explorer-enabled: false

