/*
 * Team API
 *  The team API lets you manage users, departments, locations, and cards. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: developer-access@brex.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiCallback;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiResponse;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.Pair;
import com.konfigthis.client.ProgressRequestBody;
import com.konfigthis.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.konfigthis.client.model.CreateLocationRequest;
import com.konfigthis.client.model.LocationResponse;
import com.konfigthis.client.model.PageLocationResponse;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.ws.rs.core.GenericType;

public class LocationsApiGenerated {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public LocationsApiGenerated() throws IllegalArgumentException {
        this(Configuration.getDefaultApiClient());
    }

    public LocationsApiGenerated(ApiClient apiClient) throws IllegalArgumentException {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    private okhttp3.Call addNewLocationCall(CreateLocationRequest createLocationRequest, String idempotencyKey, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = createLocationRequest;

        // create path and map variables
        String localVarPath = "/v2/locations";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (idempotencyKey != null) {
            localVarHeaderParams.put("Idempotency-Key", localVarApiClient.parameterToString(idempotencyKey));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "OAuth2" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call addNewLocationValidateBeforeCall(CreateLocationRequest createLocationRequest, String idempotencyKey, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'createLocationRequest' is set
        if (createLocationRequest == null) {
            throw new ApiException("Missing the required parameter 'createLocationRequest' when calling addNewLocation(Async)");
        }

        return addNewLocationCall(createLocationRequest, idempotencyKey, _callback);

    }


    private ApiResponse<LocationResponse> addNewLocationWithHttpInfo(CreateLocationRequest createLocationRequest, String idempotencyKey) throws ApiException {
        okhttp3.Call localVarCall = addNewLocationValidateBeforeCall(createLocationRequest, idempotencyKey, null);
        Type localVarReturnType = new TypeToken<LocationResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    private okhttp3.Call addNewLocationAsync(CreateLocationRequest createLocationRequest, String idempotencyKey, final ApiCallback<LocationResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = addNewLocationValidateBeforeCall(createLocationRequest, idempotencyKey, _callback);
        Type localVarReturnType = new TypeToken<LocationResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }

    public class AddNewLocationRequestBuilder {
        private final String name;
        private String description;
        private String idempotencyKey;

        private AddNewLocationRequestBuilder(String name) {
            this.name = name;
        }

        /**
         * Set description
         * @param description Description of the location (optional)
         * @return AddNewLocationRequestBuilder
         */
        public AddNewLocationRequestBuilder description(String description) {
            this.description = description;
            return this;
        }
        
        /**
         * Set idempotencyKey
         * @param idempotencyKey  (optional)
         * @return AddNewLocationRequestBuilder
         */
        public AddNewLocationRequestBuilder idempotencyKey(String idempotencyKey) {
            this.idempotencyKey = idempotencyKey;
            return this;
        }
        
        /**
         * Build call for addNewLocation
         * @param _callback ApiCallback API callback
         * @return Call to execute
         * @throws ApiException If fail to serialize the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> createLocation 200 response </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call buildCall(final ApiCallback _callback) throws ApiException {
            CreateLocationRequest createLocationRequest = buildBodyParams();
            return addNewLocationCall(createLocationRequest, idempotencyKey, _callback);
        }

        private CreateLocationRequest buildBodyParams() {
            CreateLocationRequest createLocationRequest = new CreateLocationRequest();
            createLocationRequest.description(this.description);
            createLocationRequest.name(this.name);
            return createLocationRequest;
        }

        /**
         * Execute addNewLocation request
         * @return LocationResponse
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> createLocation 200 response </td><td>  -  </td></tr>
         </table>
         */
        public LocationResponse execute() throws ApiException {
            CreateLocationRequest createLocationRequest = buildBodyParams();
            ApiResponse<LocationResponse> localVarResp = addNewLocationWithHttpInfo(createLocationRequest, idempotencyKey);
            return localVarResp.getResponseBody();
        }

        /**
         * Execute addNewLocation request with HTTP info returned
         * @return ApiResponse&lt;LocationResponse&gt;
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> createLocation 200 response </td><td>  -  </td></tr>
         </table>
         */
        public ApiResponse<LocationResponse> executeWithHttpInfo() throws ApiException {
            CreateLocationRequest createLocationRequest = buildBodyParams();
            return addNewLocationWithHttpInfo(createLocationRequest, idempotencyKey);
        }

        /**
         * Execute addNewLocation request (asynchronously)
         * @param _callback The callback to be executed when the API call finishes
         * @return The request call
         * @throws ApiException If fail to process the API call, e.g. serializing the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> createLocation 200 response </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call executeAsync(final ApiCallback<LocationResponse> _callback) throws ApiException {
            CreateLocationRequest createLocationRequest = buildBodyParams();
            return addNewLocationAsync(createLocationRequest, idempotencyKey, _callback);
        }
    }

    /**
     *  Create location 
     *  This endpoint creates a new location. 
     * @param createLocationRequest  (required)
     * @return AddNewLocationRequestBuilder
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> createLocation 200 response </td><td>  -  </td></tr>
     </table>
     */
    public AddNewLocationRequestBuilder addNewLocation(String name) throws IllegalArgumentException {
        if (name == null) throw new IllegalArgumentException("\"name\" is required but got null");
            if (name != null && name.length() < 1) {
              throw new IllegalArgumentException("Invalid value for name. Length must be greater than or equal to 1.");
            }

        return new AddNewLocationRequestBuilder(name);
    }
    private okhttp3.Call getAllLocationsCall(String cursor, Integer limit, String name, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v2/locations";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (cursor != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("cursor", cursor));
        }

        if (limit != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("limit", limit));
        }

        if (name != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("name", name));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "OAuth2" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getAllLocationsValidateBeforeCall(String cursor, Integer limit, String name, final ApiCallback _callback) throws ApiException {
        return getAllLocationsCall(cursor, limit, name, _callback);

    }


    private ApiResponse<PageLocationResponse> getAllLocationsWithHttpInfo(String cursor, Integer limit, String name) throws ApiException {
        okhttp3.Call localVarCall = getAllLocationsValidateBeforeCall(cursor, limit, name, null);
        Type localVarReturnType = new TypeToken<PageLocationResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    private okhttp3.Call getAllLocationsAsync(String cursor, Integer limit, String name, final ApiCallback<PageLocationResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = getAllLocationsValidateBeforeCall(cursor, limit, name, _callback);
        Type localVarReturnType = new TypeToken<PageLocationResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }

    public class GetAllLocationsRequestBuilder {
        private String cursor;
        private Integer limit;
        private String name;

        private GetAllLocationsRequestBuilder() {
        }

        /**
         * Set cursor
         * @param cursor  (optional)
         * @return GetAllLocationsRequestBuilder
         */
        public GetAllLocationsRequestBuilder cursor(String cursor) {
            this.cursor = cursor;
            return this;
        }
        
        /**
         * Set limit
         * @param limit  (optional)
         * @return GetAllLocationsRequestBuilder
         */
        public GetAllLocationsRequestBuilder limit(Integer limit) {
            this.limit = limit;
            return this;
        }
        
        /**
         * Set name
         * @param name  (optional)
         * @return GetAllLocationsRequestBuilder
         */
        public GetAllLocationsRequestBuilder name(String name) {
            this.name = name;
            return this;
        }
        
        /**
         * Build call for getAllLocations
         * @param _callback ApiCallback API callback
         * @return Call to execute
         * @throws ApiException If fail to serialize the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> listLocations 200 response </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call buildCall(final ApiCallback _callback) throws ApiException {
            return getAllLocationsCall(cursor, limit, name, _callback);
        }


        /**
         * Execute getAllLocations request
         * @return PageLocationResponse
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> listLocations 200 response </td><td>  -  </td></tr>
         </table>
         */
        public PageLocationResponse execute() throws ApiException {
            ApiResponse<PageLocationResponse> localVarResp = getAllLocationsWithHttpInfo(cursor, limit, name);
            return localVarResp.getResponseBody();
        }

        /**
         * Execute getAllLocations request with HTTP info returned
         * @return ApiResponse&lt;PageLocationResponse&gt;
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> listLocations 200 response </td><td>  -  </td></tr>
         </table>
         */
        public ApiResponse<PageLocationResponse> executeWithHttpInfo() throws ApiException {
            return getAllLocationsWithHttpInfo(cursor, limit, name);
        }

        /**
         * Execute getAllLocations request (asynchronously)
         * @param _callback The callback to be executed when the API call finishes
         * @return The request call
         * @throws ApiException If fail to process the API call, e.g. serializing the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> listLocations 200 response </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call executeAsync(final ApiCallback<PageLocationResponse> _callback) throws ApiException {
            return getAllLocationsAsync(cursor, limit, name, _callback);
        }
    }

    /**
     *  List locations 
     *  This endpoint lists all locations. 
     * @return GetAllLocationsRequestBuilder
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> listLocations 200 response </td><td>  -  </td></tr>
     </table>
     */
    public GetAllLocationsRequestBuilder getAllLocations() throws IllegalArgumentException {
        return new GetAllLocationsRequestBuilder();
    }
    private okhttp3.Call getLocationByIdCall(String id, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v2/locations/{id}"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "OAuth2" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getLocationByIdValidateBeforeCall(String id, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling getLocationById(Async)");
        }

        return getLocationByIdCall(id, _callback);

    }


    private ApiResponse<LocationResponse> getLocationByIdWithHttpInfo(String id) throws ApiException {
        okhttp3.Call localVarCall = getLocationByIdValidateBeforeCall(id, null);
        Type localVarReturnType = new TypeToken<LocationResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    private okhttp3.Call getLocationByIdAsync(String id, final ApiCallback<LocationResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = getLocationByIdValidateBeforeCall(id, _callback);
        Type localVarReturnType = new TypeToken<LocationResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }

    public class GetLocationByIdRequestBuilder {
        private final String id;

        private GetLocationByIdRequestBuilder(String id) {
            this.id = id;
        }

        /**
         * Build call for getLocationById
         * @param _callback ApiCallback API callback
         * @return Call to execute
         * @throws ApiException If fail to serialize the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> getLocationById 200 response </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call buildCall(final ApiCallback _callback) throws ApiException {
            return getLocationByIdCall(id, _callback);
        }


        /**
         * Execute getLocationById request
         * @return LocationResponse
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> getLocationById 200 response </td><td>  -  </td></tr>
         </table>
         */
        public LocationResponse execute() throws ApiException {
            ApiResponse<LocationResponse> localVarResp = getLocationByIdWithHttpInfo(id);
            return localVarResp.getResponseBody();
        }

        /**
         * Execute getLocationById request with HTTP info returned
         * @return ApiResponse&lt;LocationResponse&gt;
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> getLocationById 200 response </td><td>  -  </td></tr>
         </table>
         */
        public ApiResponse<LocationResponse> executeWithHttpInfo() throws ApiException {
            return getLocationByIdWithHttpInfo(id);
        }

        /**
         * Execute getLocationById request (asynchronously)
         * @param _callback The callback to be executed when the API call finishes
         * @return The request call
         * @throws ApiException If fail to process the API call, e.g. serializing the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> getLocationById 200 response </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call executeAsync(final ApiCallback<LocationResponse> _callback) throws ApiException {
            return getLocationByIdAsync(id, _callback);
        }
    }

    /**
     *  Get location 
     *  This endpoint gets a location by ID. 
     * @param id  (required)
     * @return GetLocationByIdRequestBuilder
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> getLocationById 200 response </td><td>  -  </td></tr>
     </table>
     */
    public GetLocationByIdRequestBuilder getLocationById(String id) throws IllegalArgumentException {
        if (id == null) throw new IllegalArgumentException("\"id\" is required but got null");
            

        return new GetLocationByIdRequestBuilder(id);
    }
}
