/*
 * Team API
 *  The team API lets you manage users, departments, locations, and cards. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: developer-access@brex.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiCallback;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiResponse;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.Pair;
import com.konfigthis.client.ProgressRequestBody;
import com.konfigthis.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.konfigthis.client.model.CreateTitleRequest;
import com.konfigthis.client.model.PageTitleResponse;
import com.konfigthis.client.model.TitleResponse;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.ws.rs.core.GenericType;

public class TitlesApiGenerated {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public TitlesApiGenerated() throws IllegalArgumentException {
        this(Configuration.getDefaultApiClient());
    }

    public TitlesApiGenerated(ApiClient apiClient) throws IllegalArgumentException {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    private okhttp3.Call createNewTitleCall(CreateTitleRequest createTitleRequest, String idempotencyKey, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = createTitleRequest;

        // create path and map variables
        String localVarPath = "/v2/titles";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (idempotencyKey != null) {
            localVarHeaderParams.put("Idempotency-Key", localVarApiClient.parameterToString(idempotencyKey));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "OAuth2" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call createNewTitleValidateBeforeCall(CreateTitleRequest createTitleRequest, String idempotencyKey, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'createTitleRequest' is set
        if (createTitleRequest == null) {
            throw new ApiException("Missing the required parameter 'createTitleRequest' when calling createNewTitle(Async)");
        }

        return createNewTitleCall(createTitleRequest, idempotencyKey, _callback);

    }


    private ApiResponse<TitleResponse> createNewTitleWithHttpInfo(CreateTitleRequest createTitleRequest, String idempotencyKey) throws ApiException {
        okhttp3.Call localVarCall = createNewTitleValidateBeforeCall(createTitleRequest, idempotencyKey, null);
        Type localVarReturnType = new TypeToken<TitleResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    private okhttp3.Call createNewTitleAsync(CreateTitleRequest createTitleRequest, String idempotencyKey, final ApiCallback<TitleResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = createNewTitleValidateBeforeCall(createTitleRequest, idempotencyKey, _callback);
        Type localVarReturnType = new TypeToken<TitleResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }

    public class CreateNewTitleRequestBuilder {
        private final String name;
        private String idempotencyKey;

        private CreateNewTitleRequestBuilder(String name) {
            this.name = name;
        }

        /**
         * Set idempotencyKey
         * @param idempotencyKey  (optional)
         * @return CreateNewTitleRequestBuilder
         */
        public CreateNewTitleRequestBuilder idempotencyKey(String idempotencyKey) {
            this.idempotencyKey = idempotencyKey;
            return this;
        }
        
        /**
         * Build call for createNewTitle
         * @param _callback ApiCallback API callback
         * @return Call to execute
         * @throws ApiException If fail to serialize the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> createTitle 200 response </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call buildCall(final ApiCallback _callback) throws ApiException {
            CreateTitleRequest createTitleRequest = buildBodyParams();
            return createNewTitleCall(createTitleRequest, idempotencyKey, _callback);
        }

        private CreateTitleRequest buildBodyParams() {
            CreateTitleRequest createTitleRequest = new CreateTitleRequest();
            createTitleRequest.name(this.name);
            return createTitleRequest;
        }

        /**
         * Execute createNewTitle request
         * @return TitleResponse
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> createTitle 200 response </td><td>  -  </td></tr>
         </table>
         */
        public TitleResponse execute() throws ApiException {
            CreateTitleRequest createTitleRequest = buildBodyParams();
            ApiResponse<TitleResponse> localVarResp = createNewTitleWithHttpInfo(createTitleRequest, idempotencyKey);
            return localVarResp.getResponseBody();
        }

        /**
         * Execute createNewTitle request with HTTP info returned
         * @return ApiResponse&lt;TitleResponse&gt;
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> createTitle 200 response </td><td>  -  </td></tr>
         </table>
         */
        public ApiResponse<TitleResponse> executeWithHttpInfo() throws ApiException {
            CreateTitleRequest createTitleRequest = buildBodyParams();
            return createNewTitleWithHttpInfo(createTitleRequest, idempotencyKey);
        }

        /**
         * Execute createNewTitle request (asynchronously)
         * @param _callback The callback to be executed when the API call finishes
         * @return The request call
         * @throws ApiException If fail to process the API call, e.g. serializing the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> createTitle 200 response </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call executeAsync(final ApiCallback<TitleResponse> _callback) throws ApiException {
            CreateTitleRequest createTitleRequest = buildBodyParams();
            return createNewTitleAsync(createTitleRequest, idempotencyKey, _callback);
        }
    }

    /**
     *  Create title 
     *  This endpoint creates a new title 
     * @param createTitleRequest  (required)
     * @return CreateNewTitleRequestBuilder
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> createTitle 200 response </td><td>  -  </td></tr>
     </table>
     */
    public CreateNewTitleRequestBuilder createNewTitle(String name) throws IllegalArgumentException {
        if (name == null) throw new IllegalArgumentException("\"name\" is required but got null");
            if (name != null && name.length() < 1) {
              throw new IllegalArgumentException("Invalid value for name. Length must be greater than or equal to 1.");
            }

        return new CreateNewTitleRequestBuilder(name);
    }
    private okhttp3.Call getAllCall(String cursor, Integer limit, String name, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v2/titles";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (cursor != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("cursor", cursor));
        }

        if (limit != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("limit", limit));
        }

        if (name != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("name", name));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "OAuth2" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getAllValidateBeforeCall(String cursor, Integer limit, String name, final ApiCallback _callback) throws ApiException {
        return getAllCall(cursor, limit, name, _callback);

    }


    private ApiResponse<PageTitleResponse> getAllWithHttpInfo(String cursor, Integer limit, String name) throws ApiException {
        okhttp3.Call localVarCall = getAllValidateBeforeCall(cursor, limit, name, null);
        Type localVarReturnType = new TypeToken<PageTitleResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    private okhttp3.Call getAllAsync(String cursor, Integer limit, String name, final ApiCallback<PageTitleResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = getAllValidateBeforeCall(cursor, limit, name, _callback);
        Type localVarReturnType = new TypeToken<PageTitleResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }

    public class GetAllRequestBuilder {
        private String cursor;
        private Integer limit;
        private String name;

        private GetAllRequestBuilder() {
        }

        /**
         * Set cursor
         * @param cursor  (optional)
         * @return GetAllRequestBuilder
         */
        public GetAllRequestBuilder cursor(String cursor) {
            this.cursor = cursor;
            return this;
        }
        
        /**
         * Set limit
         * @param limit  (optional)
         * @return GetAllRequestBuilder
         */
        public GetAllRequestBuilder limit(Integer limit) {
            this.limit = limit;
            return this;
        }
        
        /**
         * Set name
         * @param name  (optional)
         * @return GetAllRequestBuilder
         */
        public GetAllRequestBuilder name(String name) {
            this.name = name;
            return this;
        }
        
        /**
         * Build call for getAll
         * @param _callback ApiCallback API callback
         * @return Call to execute
         * @throws ApiException If fail to serialize the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> listTitles 200 response </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call buildCall(final ApiCallback _callback) throws ApiException {
            return getAllCall(cursor, limit, name, _callback);
        }


        /**
         * Execute getAll request
         * @return PageTitleResponse
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> listTitles 200 response </td><td>  -  </td></tr>
         </table>
         */
        public PageTitleResponse execute() throws ApiException {
            ApiResponse<PageTitleResponse> localVarResp = getAllWithHttpInfo(cursor, limit, name);
            return localVarResp.getResponseBody();
        }

        /**
         * Execute getAll request with HTTP info returned
         * @return ApiResponse&lt;PageTitleResponse&gt;
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> listTitles 200 response </td><td>  -  </td></tr>
         </table>
         */
        public ApiResponse<PageTitleResponse> executeWithHttpInfo() throws ApiException {
            return getAllWithHttpInfo(cursor, limit, name);
        }

        /**
         * Execute getAll request (asynchronously)
         * @param _callback The callback to be executed when the API call finishes
         * @return The request call
         * @throws ApiException If fail to process the API call, e.g. serializing the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> listTitles 200 response </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call executeAsync(final ApiCallback<PageTitleResponse> _callback) throws ApiException {
            return getAllAsync(cursor, limit, name, _callback);
        }
    }

    /**
     *  List titles 
     *  This endpoint lists all titles. 
     * @return GetAllRequestBuilder
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> listTitles 200 response </td><td>  -  </td></tr>
     </table>
     */
    public GetAllRequestBuilder getAll() throws IllegalArgumentException {
        return new GetAllRequestBuilder();
    }
    private okhttp3.Call getTitleByIdCall(String id, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v2/titles/{id}"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "OAuth2" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getTitleByIdValidateBeforeCall(String id, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling getTitleById(Async)");
        }

        return getTitleByIdCall(id, _callback);

    }


    private ApiResponse<TitleResponse> getTitleByIdWithHttpInfo(String id) throws ApiException {
        okhttp3.Call localVarCall = getTitleByIdValidateBeforeCall(id, null);
        Type localVarReturnType = new TypeToken<TitleResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    private okhttp3.Call getTitleByIdAsync(String id, final ApiCallback<TitleResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = getTitleByIdValidateBeforeCall(id, _callback);
        Type localVarReturnType = new TypeToken<TitleResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }

    public class GetTitleByIdRequestBuilder {
        private final String id;

        private GetTitleByIdRequestBuilder(String id) {
            this.id = id;
        }

        /**
         * Build call for getTitleById
         * @param _callback ApiCallback API callback
         * @return Call to execute
         * @throws ApiException If fail to serialize the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> getTitleById 200 response </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call buildCall(final ApiCallback _callback) throws ApiException {
            return getTitleByIdCall(id, _callback);
        }


        /**
         * Execute getTitleById request
         * @return TitleResponse
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> getTitleById 200 response </td><td>  -  </td></tr>
         </table>
         */
        public TitleResponse execute() throws ApiException {
            ApiResponse<TitleResponse> localVarResp = getTitleByIdWithHttpInfo(id);
            return localVarResp.getResponseBody();
        }

        /**
         * Execute getTitleById request with HTTP info returned
         * @return ApiResponse&lt;TitleResponse&gt;
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> getTitleById 200 response </td><td>  -  </td></tr>
         </table>
         */
        public ApiResponse<TitleResponse> executeWithHttpInfo() throws ApiException {
            return getTitleByIdWithHttpInfo(id);
        }

        /**
         * Execute getTitleById request (asynchronously)
         * @param _callback The callback to be executed when the API call finishes
         * @return The request call
         * @throws ApiException If fail to process the API call, e.g. serializing the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> getTitleById 200 response </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call executeAsync(final ApiCallback<TitleResponse> _callback) throws ApiException {
            return getTitleByIdAsync(id, _callback);
        }
    }

    /**
     *  Get title 
     *  This endpoint gets a title by ID. 
     * @param id  (required)
     * @return GetTitleByIdRequestBuilder
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> getTitleById 200 response </td><td>  -  </td></tr>
     </table>
     */
    public GetTitleByIdRequestBuilder getTitleById(String id) throws IllegalArgumentException {
        if (id == null) throw new IllegalArgumentException("\"id\" is required but got null");
            

        return new GetTitleByIdRequestBuilder(id);
    }
}
